### ISSUE TITLE
New Configuration

### ISSUE THREAD

**Issue by joekane3** [peterdougstuart/PCWG#10]
Annoyingly the 'New' button to create a new configuration file does work.
The method ```self.NewConfiguration()``` does not exist.

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Anaconda\lib\lib-tk\Tkinter.py", line 1486, in __call__
    return self.func(*args)
  File "C:/GH/PCWG/pcwg-tool.py", line 1234, in NewAnalysis
    configDialog = AnalysisConfigurationDialog(self.root, WindowStatus(self), self.LoadAnalysisFromPath)
  File "C:/GH/PCWG/pcwg-tool.py", line 549, in __init__
    self.config = self.NewConfiguration()
AttributeError: AnalysisConfigurationDialog instance has no attribute 'NewConfiguration'
```

**Comment by joekane3** [comment]
Fixed in v0.5.3 #11
